### ISSUE TITLE
Where is the best place to merge different entities?

### ISSUE THREAD

**Issue by ZherebtsovAlexandr** [android10/Android-CleanArchitecture#100]
So, imagine that you need to complement the application. Add new entities and add list of pets to user details screen.

I think that the User ```presentation model``` should contain a list of pets.

```java
public class UserModel {

  private int userId;

  private String fullname;
  
  private List<Pet> pets;
  
  public int getUserId() {
    return userId;
  }

  public void setUserId(int userId) {
    this.userId = userId;
  }

  public String getFullname() {
    return fullname;
  }

  public void setFullname(String fullname) {
    this.fullname = fullname;
  }
  
  public List<Pet> getPets() {
    return pets;
  }

  public void setPets(List<Pet> pets) {
    this.pets = pets;
  }
 
  ...  

}
```
The question is, where should I add a list of pets to the user?

Option 1. In interactor.
Then you need to change the ```domain model```. I'll add a list of pets into the ```domain model``` to be able to returns the pets.

```java
public class GetUserDetails extends UseCase {

    private final int userId;
    private final UserRepository userRepository;
    private final PetRepository petRepository;

    @Inject
    public GetUserDetails(int userId, UserRepository userRepository, PetRepository petRepository
                          ThreadExecutor threadExecutor, PostExecutionThread postExecutionThread) {
        super(threadExecutor, postExecutionThread);
        this.userId = userId;
        this.userRepository = userRepository;
        this.petRepository = petRepository;
    }

    @Override
    protected Observable buildUseCaseObservable() {
        return Observable.zip(this.userRepository.user(this.userId),
                              this.petRepository.pets(this.userId), 
                              new Func2<User, List<Pet>, User>() {
                                  @Override
                                  public User call(User user, List<Pet> pets) {
                                      user.setPets(pets);
                                      return user;
                                  }
                          });
    }
}
```
Option 2. In presenter.
```Interactors``` can return ```observable``` and not to accept ```subscribers```. Then you can add list of pets to user model in ```presenter```. The ```domain model``` will not change.

```java
@PerActivity
public class UserDetailsPresenter implements Presenter {

  /** id used to retrieve user details */
  private int userId;

  private UserDetailsView viewDetailsView;

  private final UseCase getUserDetailsUseCase;
  private final UseCase getPetListUseCase;
  private final UserModelDataMapper userModelDataMapper;

  @Inject
  public UserDetailsPresenter(@Named("userDetails") UseCase getUserDetailsUseCase,
	                                      @Named("petList") UseCase getPetListUseCase,
                                             UserModelDataMapper userModelDataMapper) {
    this.getUserDetailsUseCase = getUserDetailsUseCase;
    this.getPetListUseCase = getPetListUseCase;
    this.userModelDataMapper = userModelDataMapper;
  }

  
  private void getUserDetails() {
	  
    Observable<UserModel> user = this.getUserDetailsUseCase
									 .execute()
									 .map(new Func1<User, UserModel>() {
												@Override
												public UserModel call(User user) {
													return this.userModelDataMapper.transform(user);
												}
    								});									
	Observable<List<Pet>> pets = this.getPetListUseCase.execute();
		
	Observable.zip(user,
                   pets,
				   new Func2<UserModel, List<Pet>, UserModel>() {
						@Override
						public UserModel call(UserModel user, List<Pet> pets) {
							user.setPets(pets);
							return user;
						}
					})
					.subscribe(new UserDetailsSubscriber());
  }

  @RxLogSubscriber
  private final class UserDetailsSubscriber extends DefaultSubscriber<UserModel> {

    @Override public void onCompleted() {
      UserDetailsPresenter.this.hideViewLoading();
    }

    @Override public void onError(Throwable e) {
      UserDetailsPresenter.this.hideViewLoading();
      UserDetailsPresenter.this.showErrorMessage(new DefaultErrorBundle((Exception) e));
      UserDetailsPresenter.this.showViewRetry();
    }

    @Override public void onNext(UserModel user) {
      UserDetailsPresenter.this.showUserDetailsInView(user);
    }
  }
}
```
Please advise which option is best? Thank!

**Comment by Trikke** [comment]
I'd wager to say this depends on your definition of a "User" in your app. Either you define that a User can always have 0 or more pets, and you can use that everywhere. Or you can define that there is a relation between User and Pet, but this is not used everywhere in the app, and thus not a core part for the User.

In the first case, you wouldn't have a PetRepository, and since Pets are directly linked to User, they are saved and loaded directly with the User.

The second case is what you are doing. The User has the option to define his Pets, but this is not integral  for the architecture of a User. I advise against using 2 Use Cases and merging those in the Presenter. A Presenter is only the glue between the View and the UseCases. There shouldn't be any business logic in the Presenter. Image if would have 4 different Presenters where you'd want to get the User and his Pets, you'd have to write this Observable zipping 4 times. You should always try to write a Use Case for, well, every Use Case you have. There should be a Use Case for "Get a User with his selected Pets". And a separate one for "Get a User". And one for "Get all possible Pets", to build a selection list, and so on.
I'd with option 1, but write it as a separate GetUserWithHisPetsUseCase.

**Comment by ZherebtsovAlexandr** [comment]
Thanks for the detailed answer. I am also inclined to option 1. The only thing that bothered is Pets is not integral for a User, but I need add Pets to User domain model. Now I understand that Pets is part of a domain, that's normally.
