### ISSUE TITLE
Schedulers.from 

### ISSUE THREAD

**Issue by IgorGanapolsky** [android10/Android-CleanArchitecture#104]
Hello,
I see in your UseCase, you are doing
`Schedulers.from(threadExecutor)`
However, why not leverage RxJava's
`Schedulers.newThread()`?  
Is there an advantage to rolling your own thread executor in your project?

Igor

**Comment by Trikke** [comment]
I'd say it is because you have complete control over your thread pool in the app. You're not relying on an external party to handle your thread pool, if they change it in a next version (for instance, increase the pool), your users could be complaining about heavy battery drain or something and you would have a hard time figuring out where it comes from, because you didn't change anything in your own codebase.

If you have control over your pool, you know how many and how long threads exist. The idea is also more extensible. You could have an image processing app and create a pool of 10 threads but with 2 dedicated only to image processing, as an example.

**Comment by IgorGanapolsky** [comment]
@Trikke Isn't that what `Schedulers.io()` does for you anyway?  See this http://reactivex.io/RxJava/javadoc/rx/schedulers/Schedulers.html#io()

**Comment by Trikke** [comment]
Yes, sure, it provides **an** implementation for a thread pool. But unless you start digging into the source code, you have no idea of what implementation that actually is. You are of course free to use that one, if it suits your current needs.
My point still remains valid, by implementing his own thread pool, the author of this project is in complete control something that can be resource-intensive.

In the end, what ever scheduler you use, it should be an implementation detail. If next week, AwesomeLibraryX create some great ThreadPoolSchedulerX that you'd want to use, it should be easy to swap out Schedulers.io() or your own implementation with that one. So the implementation should be abstracted away by an interface. But someone else created something that seems nice, isn't reason enough to actually use it.

**Comment by IgorGanapolsky** [comment]
@Trikke  Seems like a lot of unnecessary boilerplate code, but whatever.

**Comment by lenguyenthanh** [comment]
@Trikke (y)

**Comment by Trikke** [comment]
@IgorGanapolsky, i wouldn't easily dismiss this as "boilerplate". This is a matter of decoupling your code and/or wanting to have ownership over important parts of your codebase without being dependant on the whims of an external party. A recent story on this is [that Parse is shutting down](http://blog.parse.com/announcements/moving-on/). Because a lot of developers are heavily dependant on this service, they are going to have to rewrite large parts of their app because of very tight coupling between their app and the sdk and classes that Parse supplies. This is [why decoupling your code matters](https://androidchat.co/architecture/development/parse/2016/02/01/Why-decoupling-your-code-matters-a-Parse-story/). If it is decoupled and the Parse sdk is just an implementation detail, it is much easier to swap it out when something new or better comes out.
But yes, you'll have to write more code.
