### ISSUE TITLE
Data Layer with Android Dependencies

### ISSUE THREAD

**Issue by anotherhale** [android10/Android-CleanArchitecture#12]
I have only skimmed through the source code, but I noticed that the UserDataStoreFactory and the RestApiImpl have a dependency on Android libraries. This appears to break the rule for the Clean Architecture Dependency Rule: "source code dependencies can only point inwards and nothing in an inner circle can know anything at all about something in an outer circle."

Is the Android Context used for the UserDataStoreFactory and could it be removed?

Is it possible to check connectivity from RestApi without dependency on Android libraries?

I am trying to find an architecture that I can write my core library that would interface with both mobile and web apps.  I like the concepts of the Clean Architecture for this.

**Comment by android10** [comment]
The fact that data layer has dependencies with the android framework does not mean the rule is broken. Actually you need them otherwise I would not be able to fulfill the needs of that module. 

In other words I would break that rule if I had my data layer depending on the presentation layer for example and not the other way around. 
Here is the article where I explain those concepts:
http://fernandocejas.com/2014/09/03/architecting-android-the-clean-way/
