### ISSUE TITLE
Module dependencies questions

### ISSUE THREAD

**Issue by nkleban** [android10/Android-CleanArchitecture#159]
Why data module has domain module in dependencies list? Why in domain layer there is no dependency on data module? Why presentation layer has dependency on both domain and data layer?

"Data module"
`dependencies {
compile project(':domain')
}`

"Presentation module"
`dependencies {
compile project(':data')
compile project(':domain')
}`

Shouldn't it be like a straight line? 
"Presentation" depends on -> "Domain" depends on -> "Data"

**Comment by CROSP** [comment]
@nkleban  I was confused with this at first. But you what you described is `n-tier` architecture, common approach used for ages.  But in case of `Clean Architecture` more likely `Onion Architecture` is used.
This means that `DomainLayer` which is all business rules, core, kernel or whatever of your app, which should stay independent and operate only with interfaces.  
In case of this example all data flow is implemented with `RxJava`
By the way, to make it more clear `Presentation` and `Data` layer can be on the same layer, because it is outer ring, above `Domain`.   
This is how I understand this architecture. If I am wrong please let me know.  @Trikke has great understanding of this architecture, so you can read my similar question https://github.com/android10/Android-CleanArchitecture/issues/150

**Comment by nkleban** [comment]
@CROSP thank you for your explanation! I was confused by diagram where outer ring consists of only UI.
