### ISSUE TITLE
Thead never end on reexecute 

### ISSUE THREAD

**Issue by B-greg** [android10/Android-CleanArchitecture#22]
When you doesn't have network and you click on the retry button, the thread never end. O think it's come from the UseCase.execute because it's recreate the observable.

**Comment by B-greg** [comment]
Fix: The Presenter shouldn't extend DefaultSubscriber. The best way is the create a new DefaultSubscriber everytime we want to execute the UseCase.

On the Presenter, change:
  private void getUserDetails() {
    this.getUserDetailsUseCase.execute(this);
  }

To
  private void getUserDetails() {
    this.getUserDetailsUseCase.execute(new DefaultSuscriber<>);
  }

**Comment by gaojinyu** [comment]
I also encountered this problem! How can I solve

**Comment by papo2608** [comment]
I think the problem is that onError (and also onCompleted) are terminating events, what means that your Observable won't emit any new events after any of them are called.

**Comment by B-greg** [comment]
Hi i fix the issue and I create a pull request. Hope it's good for you too.

**Comment by android10** [comment]
Hey guys, I reopened this in order to solve it. 
@papo2608 you are right, both onError() and onCompleted() are terminating events: what was happening is that Observable would not emit more items after an error. 

It would have been cool to solve it with an automatic retry:
https://github.com/ReactiveX/RxJava/wiki/Error-Handling-Operators

But I opted for a simpler solutions which is to move the subscriber logic to an inner class in the use case.
https://github.com/android10/Android-CleanArchitecture/commit/d45a2cf678fbdbd37a52f7d176a9dc187fd516d5

@B-greg thanks for the PR but as I said, let's try to keep it as simple as possible: in this case I would prefer to avoid implementing an extra interface in the presenter. 

The only thing left within this bug is to write an acceptance test to cover this case.
