### ISSUE TITLE
Using UserModel, UserEntity and User classes

### ISSUE THREAD

**Issue by vpaliyX** [android10/Android-CleanArchitecture#222]
Hello, I've read your article, awesome approach and recommendations. However, is it considered a bad practice if I use the UserEntity class everywhere instead of the UserModel and User?It would not violate the Dependency Rule and the classes are the same.

**Comment by LLin233** [comment]
my understanding is if the UserEntity class (data endpoint) has been changed, you don't have to change all of other models since you should be able to reflect the changes in the mapper.

**Comment by bradroid** [comment]
It would violate layer separation because a thing from inner layer travels through all other layers. Therefore it is recommended to use different classes for different layers, although if you end up making the exact copies of your class for each layer it might be okay to use the same class across the stack.
