### ISSUE TITLE
Why not skip the domain layer?

### ISSUE THREAD

**Issue by erikash** [android10/Android-CleanArchitecture#26]
Hi,
Kudos for the great blog post and this repository! :+1: 

The thing that bugs me is that you referred to a domain layer.
In my opinion (in most of the cases) the domain layer should only exist on the server side, referring to a domain layer in the client side is misleading.

Skipping the implementation of a domain layer in the client altogether could actually save ton of work, instead of publishing updates with the "domain" object as payload and coupling it to all of the subscribers you could publish an update with a DTO as the payload to the relevant presenters.

The interactor layer is awesome, it resembles Flux architecture events and I agree is really useful, but again you could keep it and just skip the "domain" entities.

What are the tradeoffs in your opinion?

Best regards,
Erik.

**Comment by asgarddesigns** [comment]
I have been thinking the same thing myself, I guess when you don't control the APIs there may be a need. Or maybe if there is significant client-side processing, but to me it is beginning to seem irrelevant for most use-cases.

Be interested to hear any counter-cases...

**Comment by android10** [comment]
This example was meant to grow and be applied to a big application, otherwise we would be overthinking here and in the case of the domain layer would be end up being an Anemic Domain Model (http://www.martinfowler.com/bliki/AnemicDomainModel.html).
In this case I wanted my logic to have no dependencies with the framework and in the end is what solves my problem. Both the UI and Data layer are implementation details.

**Comment by caseykulm** [comment]
Since bringing up the Anemic Domain Model, wouldn't it be wrong to have the "entities" in the Data layer such as the UserEntity object in the Data Layer, and the User object in the Domain Layer. Changing the names such that the Data Layer had a ServiceUser object, and the Domain Layer had a UserEntity object seems like it would clarify the desire to avoid an Anemic Domain Model, and clarify that the Domain Layer contains the entities.

**Comment by android10** [comment]
@caseykulm this example was meant to be for an app that is gonna scale. In this case the Domain Layer turns out to be sort of Anemic Domain Model, but within an app that has complex logic and many use cases I doubt you will end up using domain classes for only data conversion and transportation.

**Comment by caseykulm** [comment]
I was just thinking that in terms of the Dependency Rule and Uncle Bob's Clean Architecture with the Entities as the objects that everything depends on, that in this project that object would be the User object in the domain layer, and that should be thought of as an Entity. 

The UseCases are built from the User object in the domain layer, and the data from the disk/backend is parsed with GSON to a ServiceObject that is then mapped to a User object in the domain layer. The User object in the domain layer knows nothing of the presentation layer, it knows nothing of the UseCases, it knows nothing of the data layer, so it sounds a lot like an Entity to me. Am I missing something?

**Comment by caseykulm** [comment]
For example, if the data coming from the backend starting coming in a different format, but the root data to be drawn out of it was the same, then the UserServiceObject (in the data layer) would change, but the UserEntity (in the domain layer) would not.
