### ISSUE TITLE
Seems Like DiskUserDataStore Calling From main Thread

### ISSUE THREAD

**Issue by drayan85** [android10/Android-CleanArchitecture#261]
I Have added the below Line in `DiskUserDataStore` class

``` 
@Override
public Observable<UserEntity> userEntityDetails(final int userId) {
     System.out.println("DiskUserDataStore Thread ID : " + Thread.currentThread().getId());
     return this.userCache.get(userId);
}
```

It is Printing below Line:

`01-25 13:45:39.470 3117-3117/com.fernanependocejas.android10.sample.presentation I/System.out: DiskUserDataStore Thread ID : 1`

Is that mean that method has been executed in main thread instead of running in one of the thread which should have been created in JobExecutor Thread pool?

**Comment by mjohenneken** [comment]
you code is running on main Thread if `Thread.currentThread().getName.equals("main");`

**Comment by drayan85** [comment]
@mjohenneken yeah, I can see that method is executed in the main thread.  I didn't change any code from this repository after clone. I am just wondering it suppose to run on worker thread which is created in JobExecutor Thread pool.

**Comment by alexwhb** [comment]
@drayan85 I could be wrong, but I'm pretty sure it's fine for that to be running on the main thread... what you should be checking is if `this.userCache.get(userId)` is being called on the main thread, since that's actually the observable. Anything outside the observable chain will not run on your thread executor. so... if you did this: ```@Override
public Observable<UserEntity> userEntityDetails(final int userId) {
     return this.userCache.get(userId).map(val->{
           System.out.println("DiskUserDataStore Thread ID : " + Thread.currentThread().getId());
           return val;
         });
}```

That should be on the executor thread, because it's part of the observable chain. I hope that makes sense.

**Comment by drayan85** [comment]
@alexwhb Thanks. I got the point.
