### ISSUE TITLE
Why is data layer defined as "android library" plugin?

### ISSUE THREAD

**Issue by urosjarc** [android10/Android-CleanArchitecture#290]
I'm confused with the fact that you are using ["android library" in data layer](https://github.com/android10/Android-CleanArchitecture/blob/master/data/build.gradle#L10) because the data layer should not know what is happening on the presentation layer...

Why is it so? Did I miss something?

**Comment by alexwhb** [comment]
@urosjarc It does not matter what frameworks or libraries you use in the data layer... you can use what ever you want. What matters is that there is a clear abstraction between what's happening in the data layer and the presentation layer using interfaces. Those interfaces hide the details of what is happening in the data layer. But in this particular case the data layer must use the android library, because it's using Sqlite to do it's data management. What you would not want to do is allow your presentation layer to talk directly to your data layer... or have your data layer talk directly to your presentation layer... also you would not want your data layer to directly effect your UI. I hope that makes sense.

**Comment by urosjarc** [comment]
Thanx for the explanation.
