### ISSUE TITLE
dependency with transitive=true

### ISSUE THREAD

**Issue by Rainer-Lang** [android10/Android-CleanArchitecture#37]
How should I include this in dependencies.gradle:
```java
compile('com.abc:xyz:1.1.1@aar') {
    transitive = true
}
```

**Comment by android10** [comment]
you cannot, you have to do it in your build.gradle file:

```
  compile (presentationDependencies.rxJava) {
    transitive = true
  }
```

**Comment by aldoKelvianto** [comment]
Just remove the `aar` and you can also` remove transitive = true.`

aar notation will not download it's dependencies, that's why you need to add `transitive true`. I test this approach (on [CrashLytics](https://github.com/crashlytics) and [Advanced Recycler View libraries](https://github.com/h6ah4i/android-advancedrecyclerview)) and it works. 

see this: [StackOverflow](http://stackoverflow.com/questions/31731014/what-does-transitive-true-in-gradle-exactly-do-w-r-t-crashlytics) and [Gradle Docs](https://docs.gradle.org/current/userguide/dependency_management.html)
