### ISSUE TITLE
Subscription leak when executing the same UseCase multiple times

### ISSUE THREAD

**Issue by kaciula** [android10/Android-CleanArchitecture#68]
The UseCase class keeps a reference to the subscription and it is assumed that the execute() call is paired with the unsubscribe() call. However this is not always the case. 

For example, in UserListPresenter, we call execute() when we create the UserListFragment but we also call execute() when we use the retry button. So, we overwrite the subscription field without first unsubscribing from the previous subscription.

I think using a CompositeSubscription instead of a basic Subscription would solve this issue. Am I missing someting?

**Comment by Rainer-Lang** [comment]
Interesting question.

**Comment by spirosoik** [comment]
It will be good to check this also, you will solve your problem @kaciula 

https://github.com/trello/RxLifecycle

**Comment by qazt482** [comment]
So far, I've always seen the use of CompositeSubscription being used in other projects to handle the android lifecycle events, yet there's no sign of one here.

**Comment by android10** [comment]
This was fixed here: https://github.com/android10/Android-CleanArchitecture/commit/ee50c079b4d60e5545f2d50cf1eb167e75d1c2c8

And here:
https://github.com/android10/Android-CleanArchitecture/commit/a4f207e9f6460a518e4f99d3ed36fd7a22a9ea13

LeakCanary was also added in order to detect leaks here:
https://github.com/android10/Android-CleanArchitecture/commit/b03050783aa5f956fb922129db85b451c52bde3d
