### ISSUE TITLE
Frameworks usage in the Domain layer

### ISSUE THREAD

**Issue by AlexTimonin** [android10/Android-CleanArchitecture#80]
According to Uncle Bob, the domain layer should not have any clue about what type of system we are dealing with (Web/Desktop/Android) nor what frameworks are used. Here we have RXJava and Dagger tightly coupled to every layer of the project. Now, I get it that RXJava is more of a philosophy than just a library, but still: everything is coupled to it. And Dagger. The rule of abstracting away from all the implementation details is violated. Are these kinds of exceptions acceptable? And where's the borderline?

**Comment by Trikke** [comment]
I'd wager to say you are taking the "rules" a bit to strict. The domain layer should be as bare-boned as possible and should indeed only contain business logic ( usually use cases and some objects which control access/rules ). It should indeed not know about what environment it is run on, being Web/desktop/Android/iOS or implementations of the data layer, which could be sql/textfiles/binary blobs/external services only.

The thing about "domain shouldn't know about the frameworks", only applies to the above. You cannot include any Android-only framework because the Domain would then know about the environment. And by Android-only, I mean, frameworks that directly interface with android. Either something that interfaces with Activities/fragments/view/... (which is GUI, so Presentation), or stuff that interfaces with Sqlite/content providers/data loaders (which belongs in Data). Such a framework has a tight coupling to the Android SDK, so the Domain would know about Android, that that is indeed a violation. This is why in this repository, the Domain Module is Java only. Dagger and RxJava for instance are just Java frameworks ( we happen like them a lot on Android ). They don't tell the Domain anything about the environment. You can also use Dagger even if you would make a project based on Swing or AWT. If Dagger used something of Android directly (like the Activity class), then we'd have a problem.

The "rule" about frameworks should be taken more lightly. Image you have a lot of business logic that also involves validating a lot of object properties. There's no need to reinvent the wheel. If there is a small framework written in Java only that does all that validation you need in your Domain, then feel free to use it.

**Comment by AlexTimonin** [comment]
Makes perfect sense, thank you!
